version: "3.8"

services:
  ai-content-maker:
    build: .
    container_name: ai_content_maker
    restart: always

    ports:
      - "4000:4000"

    env_file:
      - .env

    environment:
      - NODE_ENV=production